import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";

const Nunitofont = Nunito({ subsets: ["latin"], weight: ["400", "700"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Nunitofont.className}>{children}</body>
    </html>
  );
}
